"""Optional Streamlit dashboard for generated benchmark artifacts.

Run from the repo root with:

    streamlit run dashboards/streamlit_app.py

Streamlit is intentionally optional so the core simulator keeps lightweight
dependencies. The static dashboard at outputs/dashboard.html is always
generated by the CLI compare command.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "benchmarks" / "results" / "benchmark_results.csv"
PLOTS = ROOT / "outputs" / "plots"
DIAGRAMS = ROOT / "docs" / "diagrams"

st.set_page_config(page_title="Semantic KV Fabric", layout="wide")
st.title("Semantic KV Control Plane")
st.caption("Rack-scale memory-orchestrated inference simulation. Simulation only.")

if RESULTS.exists():
    df = pd.read_csv(RESULTS)
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Benchmark rows", len(df))
    c2.metric("Best throughput", f"{df['estimated_throughput_score'].max():.2f}")
    c3.metric("Max avoided movement", f"{df['bytes_avoided'].max() / (1024**3):.1f} GB")
    c4.metric("Min energy/token", f"{df['energy_per_token'].min():.2e} J")
    st.subheader("Policy Results")
    st.dataframe(df, use_container_width=True)

st.subheader("Topology")
st.image(str(DIAGRAMS / "rack_scale_kv_fabric.svg"), use_container_width=True)

left, right = st.columns(2)
for idx, image in enumerate(sorted(PLOTS.glob("*.png"))):
    with (left if idx % 2 == 0 else right):
        st.image(str(image), caption=image.stem.replace("_", " ").title(), use_container_width=True)
